# Generated by Django 4.0.4 on 2022-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
