# Generated by Django 4.0.4 on 2022-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_comments_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='order',
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
