# Generated by Django 4.0.4 on 2022-05-31 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality', '0003_remove_comments_order_block_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='block',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='block',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='block',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='block',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='relation',
        ),
        migrations.AddField(
            model_name='block',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenario',
            name='block_order',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=None, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.block')),
                ('scenario_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.scenario')),
            ],
        ),
    ]
