# Generated by Django 4.0.4 on 2022-06-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_comments_writer_review_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quality.comments'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='drawio',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
